name: Bug Report
description: File a bug report to help us improve the project
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of the issue.
      placeholder: |
        Describe the issue you encountered and what you expected to happen.
        Example: "When I executed ghfetch on my terminal: {konsole}, it didn't execute."
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Run the exact command which produced this error.
        2. Check for any error-logs if it generated.
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What should have happened instead?
      placeholder: "Example: I expected a proper ascii-art on left and stats on right like other fetch programs."
      render: markdown

  - type: textarea
    attributes:
      label: Screenshots / logs
      description: Paste any error logs or add screenshots if applicable.
      placeholder: "[insert-image of issue that persists] with suitable caption."
      render: markdown

  - type: textarea
    attributes:
      label: Additional context
      description: Any other details or edge cases that might be related.
      placeholder: "This only happens when I execute the command in konsole terminal-emulator."
      render: markdown

